# Generated by Django 2.1.1 on 2018-09-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='cs_categry',
            new_name='cs_category',
        ),
        migrations.AlterField(
            model_name='course',
            name='cs_category',
            field=models.ForeignKey(on_delete=True, to='course.category'),
        ),
    ]
