# Generated by Django 2.1.1 on 2018-10-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
        ('course', '0007_auto_20181002_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cs_career',
            field=models.ForeignKey(default=1, on_delete=True, to='career.career'),
        ),
        migrations.AlterField(
            model_name='course',
            name='cs_category',
            field=models.ForeignKey(on_delete=True, to='course.category'),
        ),
    ]
