# Generated by Django 2.1.1 on 2018-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20181002_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=255)),
                ('upload', models.DateTimeField()),
                ('chapter', models.ForeignKey(on_delete=True, to='course.chapter')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='cs_category',
            field=models.ForeignKey(on_delete=True, to='course.category'),
        ),
    ]
