# Generated by Django 2.1.1 on 2018-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181005_0934'),
        ('course', '0015_auto_20181005_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecttime', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=True, to='course.section')),
                ('user', models.ForeignKey(on_delete=True, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchtime', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=True, to='course.section')),
                ('user', models.ForeignKey(on_delete=True, to='user.user')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='cs_category',
            field=models.ForeignKey(on_delete=True, to='course.category'),
        ),
    ]
