# Generated by Django 2.1.1 on 2018-10-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20181008_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cs_category',
            field=models.ForeignKey(on_delete=True, to='course.category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='learn',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
