# Generated by Django 2.1.1 on 2018-10-21 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_auto_20181020_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='section',
        ),
        migrations.AddField(
            model_name='collection',
            name='course',
            field=models.ForeignKey(default=1, on_delete=True, to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='cs_category',
            field=models.ForeignKey(on_delete=True, to='course.category'),
        ),
    ]
