# Generated by Django 2.1.1 on 2018-10-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0039_auto_20181023_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cs_category',
            field=models.ForeignKey(on_delete=True, to='course.category'),
        ),
        migrations.AlterField(
            model_name='sectioncomment_like',
            name='section',
            field=models.ForeignKey(on_delete=True, to='course.sectioncomment'),
        ),
    ]
