# Generated by Django 2.1.1 on 2018-10-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181005_0934'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collecttime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=True, to='article.article')),
                ('user', models.ForeignKey(on_delete=True, to='user.user')),
            ],
        ),
    ]
