# Generated by Django 2.1.1 on 2018-10-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='introduce',
            field=models.CharField(max_length=255),
        ),
    ]
