# Generated by Django 2.1.1 on 2018-10-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20181008_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=True, to='user.userdetail'),
        ),
        migrations.AlterField(
            model_name='article_collection',
            name='user',
            field=models.ForeignKey(on_delete=True, to='user.userdetail'),
        ),
    ]
