# Generated by Django 2.1.1 on 2018-10-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20181008_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='userinfo',
        ),
        migrations.RenameField(
            model_name='article_collection',
            old_name='user',
            new_name='userinfo',
        ),
    ]
