# Generated by Django 2.1.1 on 2018-10-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_name'),
        ('article', '0005_auto_20181008_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=True, to='article.article')),
                ('user', models.ForeignKey(on_delete=True, to='user.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=True, to='article.article')),
                ('user', models.ForeignKey(on_delete=True, to='user.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='comment_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('uptime', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=True, to='article.comment')),
                ('user', models.ForeignKey(on_delete=True, to='user.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='comment_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=True, to='article.comment')),
                ('user', models.ForeignKey(on_delete=True, to='user.userdetail')),
            ],
        ),
    ]
