# Generated by Django 2.1.1 on 2018-10-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_name'),
        ('article', '0006_article_like_comment_comment_comment_comment_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_comment_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment_comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment_comment_like',
            name='comment_comment',
            field=models.ForeignKey(on_delete=True, to='article.comment_comment'),
        ),
        migrations.AddField(
            model_name='comment_comment_like',
            name='user',
            field=models.ForeignKey(on_delete=True, to='user.userdetail'),
        ),
    ]
