# Generated by Django 2.1.1 on 2018-10-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_name'),
        ('article', '0008_auto_20181022_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_comment_like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_comment', models.ForeignKey(on_delete=True, to='article.comment_comment')),
                ('user', models.ForeignKey(on_delete=True, to='user.userdetail')),
            ],
        ),
    ]
