# Generated by Django 2.1.1 on 2018-10-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('introduce', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('learn', models.IntegerField(default=0)),
                ('finish', models.CharField(max_length=255)),
            ],
        ),
    ]
