# Generated by Django 2.1.1 on 2018-10-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='validate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='icon',
            name='iconurl',
            field=models.CharField(max_length=255),
        ),
    ]
