# Generated by Django 2.1.1 on 2018-10-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181018_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='registertemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20)),
                ('validate', models.CharField(max_length=20)),
                ('expiretime', models.BigIntegerField()),
            ],
        ),
    ]
