# Generated by Django 2.1.1 on 2018-10-23 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0037_auto_20181023_0845'),
        ('user', '0007_auto_20181022_1833'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='course',
            field=models.ForeignKey(default=1, on_delete=True, to='course.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='jointime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='status',
            name='user',
            field=models.ForeignKey(default=1, on_delete=True, to='user.userdetail'),
            preserve_default=False,
        ),
    ]
