# Generated by Django 2.1.1 on 2018-10-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181022_1833'),
        ('course', '0038_auto_20181023_0853'),
        ('order', '0002_auto_20181023_0845'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursecat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jointime', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=True, to='course.course')),
                ('user', models.ForeignKey(on_delete=True, to='user.userdetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='status',
            name='course',
        ),
        migrations.RemoveField(
            model_name='status',
            name='jointime',
        ),
        migrations.RemoveField(
            model_name='status',
            name='user',
        ),
    ]
