# Generated by Django 2.1.1 on 2018-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20181023_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecat',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
